### ISSUE TITLE
What's the effect of discrete textural features?

### ISSUE THREAD

**Issue by 07hyx06** [USTC-JialunPeng/Diverse-Structure-Inpainting#13]
Hi! Thanks for your great work.

I wonder about the effect of discrete textural features.  It seems that these discrete textural features do not enroll in the image generation part. Are the benefits to splits structural and textural features are better disentanglement?

**Comment by USTC-JialunPeng** [comment]
Yes. We believe the hierarchical VQ-VAE can robustly disentangle discrete structural and textural features. We don't use discrete textural features in the image generation part because they loss some key textural information in the lossy compression of VQ-VAE. We re-use the encoder of the hierarchical VQ-VAE to extract structural and textural features from the final inpainting result to calculate two feature losses based on their distances from discrete structural and textural features of ground truth.

**Comment by 07hyx06** [comment]
Is it means that the hierarchical VQ-VAE archtectutre can implicit disentangle structural and textural features? Since there are no explicit loss function or design to constrain the disentanglement...

**Comment by USTC-JialunPeng** [comment]
The constrain is the sizes of structural and textural features. Structural features which of smaller size capture global information, and textural features which of larger size capture local information.
