### ISSUE TITLE
Use of VQ-VAE in test.py

### ISSUE THREAD

**Issue by saeidnp** [USTC-JialunPeng/Diverse-Structure-Inpainting#4]
I am wondering if there is a discrepancy between the how inference is explained in the paper and how it is implemented in `test.py`. To be specific, the paper says "During inference, only Gs and Gt are used." but the VQ-VAE model is loaded in test.py and used to do inference (see [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L150) and [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L158) for example).

I am new to tensorflow and not super familiar with VQ-VAE, so I might be missing something, but I think since the VQ-VAE encoder is getting the full image as input (see [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L150)) there might information leak from the full image to the inpainting module at inference time. Please correct me if I'm wrong.

Thank you.

**Comment by USTC-JialunPeng** [comment]
Thanks for your good questions. Here are our responses.

1. Even though we load the hierarchical encoder and the decoder of VQ-VAE in `test.py` (see [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L150) and [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L151)), we don't use them in the inpainting procedure. We only use the fixed structural codebook (see `enc_gt['embed_t']` at [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L158)) to map the predicted index onto the predicted feature vector at the current position.

2. Similar to the first response, we don't use the encoder or decoder of VQ-VAE, except for the fixed structural codebook (a 512*64 matrix). If you are concerned about the information leak from the full image, you can replace the `batch_pos` with `masked` (see [here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/test.py#L150)) or even an all-zero tensor. The performance will be the same because we only use the fixed structural codebook.

Best wishes,
Jialun

**Comment by saeidnp** [comment]
Thank you Jialun. It clarified my confusion.

Best,
Saeid.
